trigger:
  branches:
    include:
    - '*'
 
steps:
- task: Npm@1
  inputs:
    workingDir: server
    verbose: false
  displayName: 'npm install'
 
- task: Npm@1
  inputs:
    workingDir: server
    verbose: false
    customCommand: 'run build'
  displayName: 'npm build'
 
- task: Npm@1
  inputs:
    workingDir: server
    verbose: false
    customCommand: 'run postBuildUnInstall'
  displayName: 'npm post build un-install'
 
- task: Npm@1
  inputs:
    workingDir: server
    verbose: false
    customCommand: 'run installProd'
  displayName: 'npm production install'
 
- task: Npm@1
  inputs:
    workingDir: server
    verbose: false
    customCommand: 'run postInstallProd'
  displayName: 'npm post production install'
 
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: server/dist
    artifact: 'server-dist'
  displayName: 'Publish Pipeline Artifact'
