trigger:
  branches:
    include:
    - '*'
 
steps:
 - task: Npm@1
   inputs:    
     workingDir: client  
     verbose: false
   displayName: 'npm install'
 
 - task: Npm@1  
   inputs:
     workingDir: client    
     #command: custom  \
     verbose: false  
     customCommand: 'run build'
   displayName: 'npm custom'
