trigger:
  - main

variables:
  buildConfiguration: 'Release'

pool:
  vmImage: 'ubuntu-latest'
 
steps:
# Azure Key Vault v2
# Download Azure Key Vault secrets.

- task: AzureKeyVault@2
  inputs:
    azureSubscription: Orange-Carrot-Prod-Ext-Authenticated-01
    KeyVaultName: KV-Prod-Ext-Shared-01
    SecretsFilter: 'azure-static-web-apps-api-token' # string. Required. Secrets filter. Default: *.
    #RunAsPreJob: false # boolean. Make secrets available to whole job. Default: false.

- checkout: self
  submodules: true
 
- task: AzureStaticWebApp@0
  displayName: 'Static Web App: '
  env:
    azure_static_web_apps_api_token: $(azure_static_web_apps_api_token)
  inputs:
    workingDirectory: '$(System.DefaultWorkingDirectory)/_instock-client-CI-main/client-dist'
    #app_location: '/build'
    #api_location: 'api'
    #output_location: '/output'
    skip_app_build: false
    skip_api_build: false
    is_static_export: false
    verbose: false
    azure_static_web_apps_api_token: $(azure-static-web-apps-api-token)
